openapi: 3.0.0
servers:
  - url: 'http://localhost:9200/api'
    description: Dev server (uses test data)
info:
  version: 0.0.2
  title: Servicio Santander
  contact:
    email: soporte@flow.cl
tags:
  - name: health
    description : 'Permite comprobar el funcionamiento del servicio'
  - name: order
    description: 'Permite gestionar órdenes de pago '
  - name: webhook
    description: 'Permite notificar pago en Santander'
paths:
  /v1/health:
    get:
      tags:
        - health
      summary: Comprobar funcionamiento del servicio
      description: 'Este método se utiliza para comprobar el funcionamiento del servicio.'
      responses:
        '200':
          description: 'Objeto Health'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthOk'
        '500':
          $ref: '#/components/responses/InternalServer'
  /v1/order/create:
    post:
      tags:
        - order
      summary: Crear orden de pago
      description: Este método se utiliza para crear una nueva orden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '200':
          description: Objeto Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
        '400':
          $ref: '#/components/responses/BusinessError'
        '500':
          $ref: '#/components/responses/InternalServer'
  /v1/webhook/notify:
    post:
      tags:
        - webhook
      summary: Notificación de pago consolidado
      description: Recibe una notificación cuando el pago se ha realizado en Santander
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyRequest'
      responses:
        '200':
          description: Objeto Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotifyResponse'
        '500':
          $ref: '#/components/responses/InternalServer'
  /v1/redirect:
    post:
      tags:
        - webhook
      summary: Notificación de pago consolidado
      description: Recibe una notificación cuando el pago se ha realizado en Santander
      parameters:
        - name: IdCarro
          in: path
          description: Identificador del Carro
          required: true
          schema:
            type: integer
            example: 169402
        - name: CodRet 
          in: path
          description: Codigo de Retorno (000=Pago aceptado por el banco, 001=Error en operación, 002=Pago pendiente de firma)
          required: true
          schema:
            type: string
            example: 000
        - name: Estado 
          in: path
          description: Estado del pago
          required: true
          schema:
            type: string
            example: "ACEPTADO" 
        - name: mpfin
          in: path
          description: Estructura XML MPFIN
          required: true
          schema:
            type: string
            example: <MPFIN><IDTRX>000100</IDTRX><CODRET></CODRET><NROPAGOS></NROPAGOS><TOTAL>1199</TOTAL><INDPAGO></INDPAGO><IDREG></IDREG></MPFIN>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MpfinRequest'
      responses:
        '200':
          description: Url de retorno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MpfinResponse'
        '500':
          $ref: '#/components/responses/InternalServer'
components:
  responses:
    BusinessError:
      description: 'Error de formato o negocio'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BusinessError'
    NotFound:
      description: 'Servicio o recurso no encontrado'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
    InternalServer:
      description: 'Error interno'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'
  schemas:
    HealthOk:
      type: object
      properties:
        status:
          type: string
          description: Respuesta exitosa
          example: 'Ok'
    CreateOrderRequest:
      type: object
      properties:
        uuid:
          type: string
          description: Identificador único de request
          example: "6e3058b5-5c30-4037-9dd8-8b3b17b1e69643243"
          nullable: false
        order:
          type: object
          description: Información de la orden
          nullable: false
          properties:
            id:
              type: integer
              description: Id de la orden
              example: 800130
              nullable: false
            product_id:
              type: integer
              description: Id del producto
              example: 150
              nullable: false
            method_id:
              type: integer
              description: Id del medio de pago
              example: 150
              nullable: false
            url_confirmation:
              type: string
              description: Url de confirmacion
              example: "https://flow.cl/confirmacion.php"
              nullable: false
            url_return:
              type: string
              description: url de retorno
              example: "https://flow.cl/retorno.php"
              nullable: false
            attempt_number:
              type: integer
              description: Número de intento de pago
              example: 5
              nullable: false
            amount:
              type: number
              description: Monto de la orden
              example: 10000
              nullable: false
            currency:
              type: string
              description: Moneda de la orden
              example: "PEN"
              nullable: false
            subject:
              type: string
              description: Asunto del pago
              example: "Test integracion"
              nullable: false
            expiration: 
              type: integer
              description: tiempo de expiracion de la url de pago
              example: 1703174767
              nullable: false
            email_paid:
              type: string
              description: Email de pagador
              example: test@flow.cl
            extra_params:
              type: array
              nullable: true
              description: Los parámetros adicionales de la transacción de pago
              items:
                $ref: '#/components/schemas/Metadata'
        user:
          type: object
          description: Detalles del usuario (comercio)
          properties:
            id:
              type: integer
              description: ID del usuario
              example: 200
              nullable: false
            email:
              type: string
              description: Email del usuario
              example: "test@flow.cl"
              nullable: false
            legal_name:
              type: string
              description: Razón social o nombre legal del comercio.
              example: "FLOW S.A"
              nullable: false
            tax_id:
              type: string
              description: Identificador tributario
              example: "99999999-9"
              nullable: false
            address:
              type: string
              description: Dirección tributaria de la empresa
              example: "Providencia"
              nullable: false
            fantasy_name:
              type: string
              description: Nombre de fantasía.
              example: "Pasarela de pago FLOW."
              nullable: true
    CreateOrderResponse:
      type: object
      properties:
        uuid:
          type: string
          description: Identificador único de la respuesta
          example: "123e4567-e89b-12d3-a456-426614174000"
        payment_uuid:
          type: string
          maxLength: 12
          description: ID de la orden
          example: "oca1k8nhhigb"
        provider_id:
          type: string
          description: ID de Santander
          example: "000400"
        type:
          type: string
          enum: 
            - "QR_CODE"
            - "REDIRECT"
          description: Tipo de respuesta, puede ser REDIRECT o QR_CODE
          example: "REDIRECT"
        amount:
          type: number
          description: Monto de la orden
          example: 10000.00
        currency:
          type: string
          description: Moneda de la orden
          example: "PEN"
        url:
          type: string
          description: QR o Redirect URL
          example: "https://khipu.com/payment/info/oca1k8nhhigb"
        expire_time:
          type: number
          description: Tiempo de expiración del QR
          example: 300
        expire_date:
          type: string
          description: Fecha de expiración del QR
          example: "2023-09-29 08:55:53"
        fields:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Metadata'
    NotifyRequest:
      type: object
      properties:
        TX:
          type: array
          description: Array con campos de request
        TX.CODRET:
          type: number
          maxLength: 4
          description: Codigo retorno operación
          example: 0000
        TX.DESCRET:
          type: string
          maxLength: 200
          description: Descripcion codigo retorno asociado a operación
          example: 'OK'  
        TX.IDCOM:
          type: string
          maxLength: 20
          description: Identificador comercio
          example: '5878'
        TX.IDTRX:
          type: number
          maxLength: 20
          description: Identificador comercio
          example: 11736793152       
        TX.TOTAL:
          type: number
          maxLength: 18
          description: Monto pagado (Con máximo 2 decimales)
          example: 27828.00  
        TX.MONEDA:
          type: string
          maxLength: 3
          description: Código moneda
          example: '999' 
        TX.NROPAGOS:
          type: number
          maxLength: 2
          description: Número de items pagados
          example: 2  
        TX.FECHATRX:
          type: string
          maxLength: 2
          description: Fecha y hora de pago (Formato DD/MM/YYYY HH:mm:ss)
          example: '07/02/2024 11:32:20' 
        TX.IDTRXREC:
          type: string
          maxLength: 20
          description: Identificador de transacción entregado por el banco para la operación
          example: '122336754'    
    NotifyResponse:
      type: object
      properties:
        code:
          type: string
          description: Código de retorno operación
          example: "000"
        dsc:
          type: string
          maxLength: 20
          description: Descripción del código de retorno asociado a la operación
          example: "Proceo exitoso"   
    MpfinRequest:
      type: object
      properties:
        IdCarro:
          type: number
          maxLength: 11
          description: Identificador carro
          example: 169485
        CodRet:
          type: string
          maxLength: 3
          description: Código de retorno
          example: '000'  
        Estado:
          type: string
          maxLength: 20
          description: Estado del pago
          example: 'ACEPTADO'
        mpfin:
          type: string
          maxLength: 20
          description: Estructura XML Mpfin
          example: '<MPFIN><IDTRX>000100</IDTRX><CODRET></CODRET><NROPAGOS></NROPAGOS><TOTAL>1199</TOTAL><INDPAGO></INDPAGO><IDREG></IDREG></MPFIN>'                
    MpfinResponse:
      type: object
      properties:
        message:
          type: string
          description: Información sobre recepción
          example: "Recepción exitosa"
        url_return:
          type: string
          maxLength: 256
          description: Url de retorno
          example: "https://flow.cl/retorno.php"  
    NotFoundError:
      type: object
      properties:
        code:
          type: number
          description: Código de error
          example: 404
        error:
          type: string
          description: Mensaje de error
          example: Not Found
    InternalServerError:
      type: object
      properties:
        code:
          type: number
          description: Código de error
          example: 500
        message:
          type: string
          description: Mensaje de error
          example: 'Internal Server Error / Id de carro inexistente'
    
