apiVersion: v1
kind: Secret
metadata:
  name: santander-secret
stringData:
  .env: |
    APP_NAME="Flow Santander"
    APP_ENV=SECRET_APP_ENV
    APP_KEY=base64:YwBL24ylPcE0O9GpYnzH87APsb3c7FSeU4tvsEGI83Y=
    APP_DEBUG=false
    APP_URL=http://localhost
    LOG_CHANNEL=SECRET_LOG_CHANNEL
    LOG_LEVEL=SECRET_LOG_LEVEL

    DB_CONNECTION=mysql
    DB_HOST=SECRET_DB_HOST
    DB_PORT=SECRET_DB_PORT
    DB_DATABASE=SECRET_DB_DATABASE
    DB_USERNAME=SECRET_DB_USERNAME
    DB_PASSWORD=SECRET_DB_PASSWORD

    QUEUE_CONNECTION=database

    KAFKA_PORT=SECRET_KAFKA_PORT
    KAFKA_BROKERS=SECRET_KAFKA_BROKERS
    KAFKA_DEBUG=SECRET_KAFKA_DEBUG
    KAFKA_COMPRESSION_TYPE=none
    KAFKA_CONSUMER_GROUP_ID=Group-1
    KAFKA_SASL_USERNAME=SECRET_KAFKA_SASL_USERNAME
    KAFKA_SASL_PASSWORD=SECRET_KAFKA_SASL_PASSWORD
