<?php

namespace App\Http\Utils;

abstract class Constants
{
    const DEFAULT_NOTIFY_API_VERSION = "1.0";
    const MAX_INTEGER_LENGTH = 11;
    const MAX_ORDER_EXPIRATION = 31536000;
    const PARAM_EXPIRATION_TIME = 900;
    const SANTANDER_AGREEMENT = '9570';
    const SANTANDER_COLLECTOR = '7683001403';

    const KAFKA_NOTIFICATION_TOPIC='KAFKA_NOTIFICATION_TOPIC';
    const PARAMETER_TABLE = 'bbs_parameter';
    const PARAM_KAFKA_PAYMENT_TYPE='KAFKA_PAYMENT_TYPE';
    const PARAM_CURRENCY='CURRENCY';
    const PARAM_URL_RETORNO='URL_RETORNO';
    const PARAM_SANTANDER_TOKEN_COMPANY = 'SANTANDER_TOKEN_COMPANY';
    const PARAM_SANTANDER_TOKEN_USERNAME = 'SANTANDER_TOKEN_USERNAME';
    const PARAM_SANTANDER_TOKEN_PASSWORD = 'SANTANDER_TOKEN_PASSWORD';
    const PARAM_SANTANDER_URL = 'SANTANDER_TOKEN_URL';
    const PARAM_SANTANDER_SFTP_HOST = 'SFTP_HOST_SANTANDER';
    const PARAM_SANTANDER_SFTP_USERNAME = 'SFTP_USERNAME_SANTANDER';
    const PARAM_SANTANDER_SFTP_PASSWORD = 'SFTP_PASSWORD_SANTANDER';
    const PARAM_ORDER_MIN_AMOUNT = 'ORDER_MIN_AMOUNT';
    const PARAM_ORDER_MAX_AMOUNT = 'ORDER_MAX_AMOUNT';
    const PARAM_ALLOWED_METHODS = 'ALLOWED_METHODS';
    
    const STATUS_CREATED = 'CREATED';
    const STATUS_PREAUTHORIZED = 'PRE-AUTHORIZED';
    const STATUS_AUTHORIZED = 'AUTHORIZED';
    const STATUS_FAILED_OP = 'FAILED_OP';
    const STATUS_FAILED_SIGN = 'FAILED_SIGN';
}
