<?php

namespace App\Http\Utils;

abstract class Constants
{
    const DEFAULT_NOTIFY_API_VERSION = "1.3";
    const DEFAULT_KHIPU_CLIENT_TIMEOUT = 30;
    const MAX_INTEGER_LENGTH = 18;
    const MAX_ORDER_EXPIRATION = 31536000;

    const PARAM_BANK_RECEIVER = '_BANK_RECEIVER';
    const PARAM_BANK_SECRET = '_BANK_SECRET';
    const PARAM_BANK_METHOD = 'BANK_METHOD_';
    const PARAM_WEBHOOK_URL = 'WEBHOOK_URL';
    const PARAM_NOTIFY_API_VERSION = 'NOTIFY_API_VERSION';
    const PARAM_KHIPU_URL = 'KHIPU_API_URL';
    const PARAM_KHIPU_TIMEOUT = 'KHIPU_CLIENT_TIMEOUT';
    const PARAM_ALLOWED_CURRENCIES = 'ALLOWED_CURRENCIES';
    const PARAM_ALLOWED_METHODS = 'ALLOWED_METHODS';
    const PARAM_KAFKA_PAYMENT_TYPE = 'KAFKA_PAYMENT_TYPE';
    const PARAM_EXPIRATION_TIME = 'ORDER_EXPIRATION_TIME';
    const KAFKA_NOTIFICATION_TOPIC = 'KAFKA_NOTIFICATION_TOPIC';
    const PARAM_MIN_AMOUNT = 'ORDER_MIN_AMOUNT';
    const PARAM_MAX_AMOUNT = 'ORDER_MAX_AMOUNT';

    const STATUS_CREATED = 'CREATED';
    const STATUS_PENDING = 'PENDING';
    const STATUS_VERIFYING = 'VERIFYING';
    const STATUS_PAID = 'PAID';
    const STATUS_CANCELED = 'CANCELED';
}
